In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv('/Users/archana/Documents/Projects/Predict Criminals/d17428d0-e-Criminal/criminal_train.csv', skiprows=[0], sep=",",header=None)


In [2]:
data

0   1   2   3   4   5   6   7   8   9  ...  61  62  63  64  65  66  \
0       4   2   4   1   3   1   1   1  99  99 ...   1   2   1   1   2   2   
1       4   1   3   1   2   1   1   1  99  99 ...   2   2   2   3   2   2   
2       4   1   2   1   2   1   1   1  99  99 ...   2   2   2   3   2   2   
3       4   0   2   1   1   1   1   1  99  99 ...   2   2   1   1   2   2   
4       1   0   6   1   4   1   1   1  99   1 ...   2   2   2   2   2   2   
5       4   0   2   1   1   1   1   1  99  99 ...   2   2   2   3   2   2   
6       4   3   6   1   4   1   1   1  99  99 ...   2   2   2   2   2   2   
7       4   2   4   1   3   1   1   1  99  99 ...   2   2   2   2   2   2   
8       4   1   3   1   2   1   1   1  99  99 ...   2   2   2   1   2   2   
9       4   0   1   1   1   1   2   1  99  99 ...   2   2   1   1   2   2   
10      4   0   1   1   1   1   1   1  99  99 ...  98  98   2   3   2   2   
11      4   0   4   1   3   1   1   1  99   1 ...   2   2   1   1   2   2   
12      4   0   2   1   1   1   2   1  99  99 ...   2   2   2   2   2   2   
13      1   0   3   1   2   1   1   1  99   1 ...   2   2   1   1   2   2   
14      1   0   5   1   4   1   1   1  99   1 ...   2   2   1   1   2   2   
15      4   3   5   1   4   1   1   1  99  99 ...   2   2   1   1   2   2   
16      4   0   2   1   1   1   1   1  99  99 ...   2   2   2   2   2   2   
17      4   2   4   1   3   1   1   1  99  99 ...   2   2   3   3   2   2   
18      4   2   3   1   3   1   1   1  99  99 ...   2   2   2   2   2   2   
19      1   0   4   1   3   1   1   1  99   1 ...   2   2   2   3   2   2   
20      1   0   4   1   3   1   1   1  99   1 ...   2   2   2   3   2   2   
21      4   1   3   1   2   1   1   1  99  99 ...   2   2   2   2   2   2   
22      1   0   5   1   3   1   2   1  99   1 ...   2   1   1   1   2   2   
23      4   0   2   1   1   1   3   1  99  99 ...   2   2   2   3   2   2   
24      1   0   6   1   4   1   1   1  99  99 ...   2   2   2   3   1   1   
25      4   0   4   1   2   1   1   1  99   1 ...   2   2   1   1   2   2   
26      4   0   3   1   2   3   1   3  99  99 ...   2   2   2   3   2   2   
27      4   0   1   1   1   1   1   1  99  99 ...   2   2   2   2   1   1   
28      4   0   3   1   1   1   1   1  99   1 ...   2   2   2   3   2   2   
29      1   0   4   1   3   1   1   1  99   1 ...   2   2   2   2   2   2   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  .. ...  ..  ..  ..  ..  ..  ..   
45686   4   0   3   1   2   1   1   1  99  99 ...   2   2   2   2   1   1   
45687   4   1   3   1   2   1   1   1  99  99 ...   2   2   2   2   2   2   
45688   1   0   4   1   3   1   1   1  99   1 ...   2   2   2   3   2   2   
45689   4   0   4   1   1   1   1   1  99  99 ...   2   2   2   2   2   2   
45690   4   2   3   1   3   1   1   1  99  99 ...   2   2   2   2   2   2   
45691   4   0   2   1   1   1   1   1  99  99 ...   2   2   1   1   2   2   
45692   4   2   4   1   3   1   1   1  99  99 ...   2   2   2   2   2   2   
45693   4   3   6   1   4   1   1   1  99  99 ...   2   2   1   1   2   2   
45694   4   0   3   1   1   1   1   1  99  99 ...   2   2   1   1   2   2   
45695   4   0   3   1   1   1   2   1  99  99 ...   2   2   1   1   2   2   
45696   4   0   4   1   1   1   1   1  99  99 ...   2   2   1   1   2   2   
45697   1   0   4   1   3   1   1   1  99   1 ...   2   2   1   1   2   2   
45698   1   0   3   1   2   1   1   1  99   1 ...   2   1   2   2   2   2   
45699   4   0   4   1   1   1   1   1  99  99 ...   2   2   1   1   2   2   
45700   4   3   5   1   4   1   1   1  99  99 ...   2   2   1   1   2   2   
45701   1   0   4   1   3   1   1   1  99   1 ...   2   2   1   1   2   2   
45702   4   3   6   1   4   1   1   1  99  99 ...   2   2   2   3   2   2   
45703   4   1   2   1   2   1   1   1  99  99 ...   2   2   2   2   2   2   
45704   4   0   3   1   1   1   2   1  99  99 ...   2   2   1   1   2   2   
45705   4   2   4   1   3   1   1   1  99   1 ...   2   2   3   3   2   2   
457

In [3]:
from sklearn.model_selection import train_test_split
X = np.array(data.drop([68],1))
y = np.array(data[68])


In [6]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(X)
df_normalized = pd.DataFrame(np_scaled)
df_normalized

0         1    2    3         4    5    6    7    8    9  ...   \
0      1.000000  0.666667  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  1.0 ...    
1      1.000000  0.333333  0.4  0.0  0.333333  0.0  0.0  0.0  1.0  1.0 ...    
2      1.000000  0.333333  0.2  0.0  0.333333  0.0  0.0  0.0  1.0  1.0 ...    
3      1.000000  0.000000  0.2  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...    
4      0.000000  0.000000  1.0  0.0  1.000000  0.0  0.0  0.0  1.0  0.0 ...    
5      1.000000  0.000000  0.2  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...    
6      1.000000  1.000000  1.0  0.0  1.000000  0.0  0.0  0.0  1.0  1.0 ...    
7      1.000000  0.666667  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  1.0 ...    
8      1.000000  0.333333  0.4  0.0  0.333333  0.0  0.0  0.0  1.0  1.0 ...    
9      1.000000  0.000000  0.0  0.0  0.000000  0.0  0.5  0.0  1.0  1.0 ...    
10     1.000000  0.000000  0.0  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...    
11     1.000000  0.000000  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  0.0 ...    
12     1.000000  0.000000  0.2  0.0  0.000000  0.0  0.5  0.0  1.0  1.0 ...    
13     0.000000  0.000000  0.4  0.0  0.333333  0.0  0.0  0.0  1.0  0.0 ...    
14     0.000000  0.000000  0.8  0.0  1.000000  0.0  0.0  0.0  1.0  0.0 ...    
15     1.000000  1.000000  0.8  0.0  1.000000  0.0  0.0  0.0  1.0  1.0 ...    
16     1.000000  0.000000  0.2  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...    
17     1.000000  0.666667  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  1.0 ...    
18     1.000000  0.666667  0.4  0.0  0.666667  0.0  0.0  0.0  1.0  1.0 ...    
19     0.000000  0.000000  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  0.0 ...    
20     0.000000  0.000000  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  0.0 ...    
21     1.000000  0.333333  0.4  0.0  0.333333  0.0  0.0  0.0  1.0  1.0 ...    
22     0.000000  0.000000  0.8  0.0  0.666667  0.0  0.5  0.0  1.0  0.0 ...    
23     1.000000  0.000000  0.2  0.0  0.000000  0.0  1.0  0.0  1.0  1.0 ...    
24     0.000000  0.000000  1.0  0.0  1.000000  0.0  0.0  0.0  1.0  1.0 ...    
25     1.000000  0.000000  0.6  0.0  0.333333  0.0  0.0  0.0  1.0  0.0 ...    
26     1.000000  0.000000  0.4  0.0  0.333333  1.0  0.0  1.0  1.0  1.0 ...    
27     1.000000  0.000000  0.0  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...    
28     1.000000  0.000000  0.4  0.0  0.000000  0.0  0.0  0.0  1.0  0.0 ...    
29     0.000000  0.000000  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  0.0 ...    
...         ...       ...  ...  ...       ...  ...  ...  ...  ...  ... ...    
45686  1.000000  0.000000  0.4  0.0  0.333333  0.0  0.0  0.0  1.0  1.0 ...    
45687  1.000000  0.333333  0.4  0.0  0.333333  0.0  0.0  0.0  1.0  1.0 ...    
45688  0.000000  0.000000  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  0.0 ...    
45689  1.000000  0.000000  0.6  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...    
45690  1.000000  0.666667  0.4  0.0  0.666667  0.0  0.0  0.0  1.0  1.0 ...    
45691  1.000000  0.000000  0.2  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...    
45692  1.000000  0.666667  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  1.0 ...    
45693  1.000000  1.000000  1.0  0.0  1.000000  0.0  0.0  0.0  1.0  1.0 ...    
45694  1.000000  0.000000  0.4  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...    
45695  1.000000  0.000000  0.4  0.0  0.000000  0.0  0.5  0.0  1.0  1.0 ...    
45696  1.000000  0.000000  0.6  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...    
45697  0.000000  0.000000  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  0.0 ...    
45698  0.000000  0.000000  0.4  0.0  0.333333  0.0  0.0  0.0  1.0  0.0 ...    
45699  1.000000  0.000000  0.6  0.0  0.000000  0.0  0.0  0.0  1.0  1.0 ...    
45700  1.000000  1.000000  0.8  0.0  1.000000  0.0  0.0  0.0  1.0  1.0 ...    
45701  0.000000  0.000000  0.6  0.0  0.666667  0.0  0.0  0.0  1.0  0.0 ...    
45702  1.000000  1.000000  1.0  0.0  1.000000  0.0  0.0  0.0  1.0  1.0 ...    
45703  1.000000  0.333333  0.2  0.0  0.333333  0.0  0.0  0.0  1.0  1.0 ...    
45704  1.000000  0.000000  0.4  0.0  0.000000  0.0  0.5  0.0  1

In [7]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.15)



In [15]:
X_train.shape

(38858, 68)

In [16]:
X_test.shape

(6858, 68)

In [17]:
y_train.shape

(38858,)

In [18]:
y_test.shape

(6858,)

In [13]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier(n_estimators = 60,max_features=4)

rnd_clf.fit(X,y)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=4, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=60, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [14]:
#X_test = X
y_pred_rf = rnd_clf.predict(X_test)

In [15]:
y_pred_rf.reshape(-1,1)

#rnd_clf.score(y_test,y_pred_rf)
y_pred_rf = y_pred_rf.reshape(-1,1)
y_pred_rf.shape

(6858, 1)

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred_rf,y_test)
#accuracy_score(y_pred_rf,y_train)

1.0

In [17]:
y_pred_rf

array([[40039],
       [40013],
       [40011],
       ..., 
       [40002],
       [40028],
       [40046]])

In [34]:
data_test = pd.read_csv('/Users/archana/Documents/Projects/Predict Criminals/d17428d0-e-Criminal/criminal_test.csv', skiprows=[0], sep=",",header=None)
test_X = np.array(data_test)

In [35]:
test_X

array([[4, 0, 4, ..., 2, 2, 1],
       [4, 0, 4, ..., 2, 2, 2],
       [2, 0, 3, ..., 2, 2, 2],
       ..., 
       [1, 0, 5, ..., 2, 2, 2],
       [4, 0, 2, ..., 2, 2, 1],
       [4, 2, 6, ..., 2, 2, 2]])

In [36]:
y_pred_test = rnd_clf.predict(test_X)

ValueError: Number of features of the model must match the input. Model n_features is 69 and input n_features is 68 

In [15]:
y_pred_test

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
a = test_X[:,0:1]
b = y_pred_test.reshape(-1,1)
b.shape

(11430, 1)

In [17]:

result = np.concatenate((a,b),axis=1)

In [18]:
result = pd.DataFrame(result)

In [19]:
result.to_csv("/Users/archana/Documents/Projects/Predict Criminals/d17428d0-e-Criminal/submission.csv")

0.93569553805774275

In [21]:
data_test = pd.read_csv('/Users/archana/Documents/Projects/Predict Criminals/d17428d0-e-Criminal/criminal_test.csv', skiprows=[0], sep=",",header=None)
test_X = np.array(data_test)

In [22]:
y_pred_test = clf.predict(test_X)

In [23]:
a = test_X[:,0:1]
b = y_pred_test.reshape(-1,1)
b.shape

(11430, 1)

In [24]:

result = np.concatenate((a,b),axis=1)

In [25]:
result = pd.DataFrame(result)
result.to_csv("/Users/archana/Documents/Projects/Predict Criminals/d17428d0-e-Criminal/submission_tree.csv")